"""EML Lab public API."""

from eml_lab.agentic import OrchestratorConfig, OrchestratorResult, run_orchestrator
from eml_lab.artifacts import ArtifactFile, ArtifactManifest
from eml_lab.benchmarks import BenchmarkResult, run_benchmark_suite
from eml_lab.campaigns import CampaignResult, run_campaign
from eml_lab.comparison import (
    ComparisonResult,
    ComparisonSuiteEntry,
    ComparisonSuiteResult,
    MethodComparisonAggregate,
    MethodComparisonAggregateRow,
    MethodComparisonExportResult,
    MethodComparisonIndexEntry,
    MethodComparisonResult,
    MethodComparisonSnapshotHistory,
    MethodComparisonSnapshotHistoryReportResult,
    MethodComparisonSnapshotIndexEntry,
    MethodComparisonSnapshotResult,
    MethodComparisonSnapshotTargetTrend,
    PySRStatus,
    aggregate_method_comparison_snapshots,
    aggregate_method_comparisons,
    detect_pysr_environment,
    export_method_comparisons,
    filter_method_comparisons,
    find_method_comparison_snapshots,
    find_method_comparisons,
    load_method_comparison,
    load_method_comparison_snapshot,
    report_method_comparison_snapshots,
    run_method_comparison,
    run_pysr_compare_suite,
    run_pysr_comparison,
    snapshot_method_comparisons,
    summarize_method_comparison_snapshots,
    summarize_method_comparisons,
    write_method_comparison_export,
    write_method_comparison_snapshot,
    write_method_comparison_snapshot_history_report,
)
from eml_lab.experiments import ExperimentRecord
from eml_lab.operator_zoo import (
    OperatorZooCandidate,
    OperatorZooConfig,
    OperatorZooEntry,
    OperatorZooResult,
    candidate_registry,
    run_operator_zoo,
)
from eml_lab.operators import StabilityConfig, StabilityStats, eml_exact, eml_train
from eml_lab.soft_tree import SoftEMLTree, snap_tree
from eml_lab.targets import TargetSpec, get_target, list_targets
from eml_lab.training import TrainConfig, TrainResult, train_target
from eml_lab.trees import TreeNode, from_rpn, to_rpn
from eml_lab.verify import VerificationReport, verify_tree

__all__ = [
    "ArtifactFile",
    "ArtifactManifest",
    "aggregate_method_comparisons",
    "BenchmarkResult",
    "CampaignResult",
    "ComparisonResult",
    "ComparisonSuiteEntry",
    "ComparisonSuiteResult",
    "ExperimentRecord",
    "OperatorZooCandidate",
    "OperatorZooConfig",
    "OperatorZooEntry",
    "OperatorZooResult",
    "candidate_registry",
    "export_method_comparisons",
    "filter_method_comparisons",
    "MethodComparisonAggregate",
    "MethodComparisonAggregateRow",
    "MethodComparisonExportResult",
    "MethodComparisonIndexEntry",
    "MethodComparisonResult",
    "MethodComparisonSnapshotHistory",
    "MethodComparisonSnapshotHistoryReportResult",
    "MethodComparisonSnapshotResult",
    "MethodComparisonSnapshotIndexEntry",
    "MethodComparisonSnapshotTargetTrend",
    "OrchestratorConfig",
    "OrchestratorResult",
    "PySRStatus",
    "aggregate_method_comparison_snapshots",
    "SoftEMLTree",
    "StabilityConfig",
    "StabilityStats",
    "detect_pysr_environment",
    "TargetSpec",
    "TrainConfig",
    "TrainResult",
    "TreeNode",
    "VerificationReport",
    "eml_exact",
    "eml_train",
    "find_method_comparisons",
    "find_method_comparison_snapshots",
    "from_rpn",
    "get_target",
    "list_targets",
    "load_method_comparison",
    "load_method_comparison_snapshot",
    "report_method_comparison_snapshots",
    "run_orchestrator",
    "run_campaign",
    "run_method_comparison",
    "run_benchmark_suite",
    "run_operator_zoo",
    "run_pysr_compare_suite",
    "run_pysr_comparison",
    "snap_tree",
    "snapshot_method_comparisons",
    "summarize_method_comparisons",
    "summarize_method_comparison_snapshots",
    "to_rpn",
    "train_target",
    "verify_tree",
    "write_method_comparison_export",
    "write_method_comparison_snapshot",
    "write_method_comparison_snapshot_history_report",
]
